# -*- coding: utf-8 -*-

FROM_UNKNOWN = 0
FROM_PLAYER = 1
FROM_SQUAD = 2
FROM_ALLY = 3
FROM_ENEMY = 4

PACK_SEPARATOR = ','
STOCK_VEHICLE_MARKER_SYMBOL = 'VehicleMarker'
DEPDAMAGE_VEHICLE_MARKER_SYMBOL = 'DepDamageVehicleMarker'
